name: Schedule Update

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.WOW_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Set up Git identity
        run: |
          git config --global user.email "${{ secrets.U_EMAIL }}"
          git config --global user.name "${{ secrets.U_NAME }}"
      # 运行
      - name: Run python
        run: python main.py
      - name: Update repo
        run: |
          git add .
          git commit -m "auto update"
          git push -u origin main
      - name: Push changes to remote repository
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.WOW_TOKEN }}
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git push origin HEAD:main
          else
            echo "No changes, skip push."
          fi
