name: Schedule Update
on:
schedule:
- cron: "0 * * * *"
workflow_dispatch: # 添加支持手动执行的事件

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: 运行 Python
        run: python main.py
      - name: Push changes to remote repository
        env:
          U_NAME: ${{ secrets.U_NAME }}
          U_EMAIL: ${{ secrets.U_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.WOW_TOKEN }}
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            pwd
            git config --local user.name "${U_NAME}"
            git config --local user.email "${U_EMAIL}"
            git add README.md
            git commit -m "Update README.md"
            git push --force origin main
          else
            echo "No changes, skip push."
          fi
