name: Schedule Update

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:  # 添加支持手动执行的事件

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WOW_TOKEN }}
    
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      # 安装 Python 依赖
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

     # 运行 Python
      - name: 运行 Python
        run: python main.py

      - name: Push changes to remote repository
        env:
          U_NAME: ${{ secrets.U_NAME }}
          U_EMAIL: ${{ secrets.U_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.WOW_TOKEN }}
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
          pwd
          git config --local user.name "${U_NAME}"  # 修改name
          git config --local user.email "${U_EMAIL}"  # 修改email
          git status -s
          git add README.md

          export TZ='Asia/Shanghai' # 更改时区
          git commit -m "Github RSS Translate Auto Builder at `date +'%Y-%m-%d %H:%M'`"  # 提交记录包含时间 跟上面更改时区配合

          echo "======git push===="
          git push --force origin main
          else
          echo "No changes, skip push."
          fi
